### ISSUE TITLE
DTD - accept both

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms11#13]
The only issue with r8, is that the RIs are not passing due to the DTD. Can we code in the CTL to allow an implementation to use either or? If using the old DTD then we can provide the result as *Warning* instead of *Failed*.

```
Test wms:wmsops-getcapabilities-response-2 (View Details): Failed
The dtd http://cite.lat-lon.de/deegree-webservices-3.3.6/services/wms?request=DTD does not match the dtd expected from the specification
```

These are the two dtds:
- old one: http://schemas.opengis.net/wms/1.1.1/WMS_MS_Capabilities.dtd (old one)
- correct one: http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd (This DTD includes all Extent attributes documented in clause C.3 (some were missing in A.1))

**Comment by dbretschneider** [comment]
We have to implement the pseudocode. In the past I tested different variants, but in all cases it does not work to check, which DTD is used.

Example:
```xml
      <xsl:for-each select="$request1">
        <xsl:choose>
          <xsl:when test="newDtd">
            ...
          </xsl:when>
          <xsl:when test="oldDtd">
            <warning/>
          </xsl:when>
          <xsl:otherwise>
            <fail/>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:for-each>
```
Do you know how the check, which DTD is used? @rjmartell

**Comment by bermud** [comment]
@rjmartell, can you please provide some guidance? This should be possible in the CTL world. Thanks.

**Comment by rjmartell** [comment]
Perhaps drop the GMLValidatingParser from here and just attempt to validate the capabilities document using the DTD referenced in the DOCTYPE declaration (whatever it is). The `com.occamlab.te.parsers.XMLValidatingParser` class (in teamengine-core) was recently updated to use schema location hints in the instance document.

Now this is known to work for XML Schema references (xsi:schemaLocation); it may also work for DTDs. I'll add some unit tests to check this.

**Comment by rjmartell** [comment]
If using teamengine 4.1.0 or later, replace  `<wms:GMLValidatingParser/>` with `<parsers:XMLValidatingParser />`. The capabilities document should then be validated against the DTD referenced in the DOCTYPE declaration.

**Comment by dbretschneider** [comment]
I have replace the GML with the XML validation parser and created a new pull request https://github.com/opengeospatial/ets-wms11/pull/25.

**Comment by bermud** [comment]
Fixed in https://github.com/opengeospatial/ets-wms11/commit/115e62d3a3fab8e80c5e659fe0d13b784455f680
Tested with Reference Implementation. OK
