### ISSUE TITLE
Verifying transparency of PNG image

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms11#20]
This service
http://107.20.228.18/arcgis/services/Wetlands/MapServer/WmsServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GETCAPABILITIES

Fails in Test wms:wmsops-getmap-params-exceptions-6 
```
Message d1e8375_1:
   [FAILED] xs:integer(//parsers:count) eq 0 is true.

Message d1e8378_1:
   Expected some pixels with an alpha value of 0 (fully transparent).

Result: Failed

```
In this test TE sends the following:
http://107.20.228.18/arcgis/services/Wetlands/MapServer/WmsServer?&VeRsIoN=1.1.1&BbOx=-1,-1,1,1&TrAnSpArEnT=TRUE&LaYeRs=NonExistant&FoRmAt=image/png&StYlEs=&ExCePtIoNs=application/vnd.ogc.se_blank&SrS=EPSG:4326&ReQuEsT=GetMap&WiDtH=100&HeIgHt=100

Server is returning a transparent image with size 100 x 100.
Why is it failing?

**Comment by dbretschneider** [comment]
I have created a Pull request (https://github.com/opengeospatial/ets-wms11/pull/21) which implements the pseudo code of https://github.com/opengeospatial/ets-wms11/issues/20#issuecomment-64467969.

**Comment by bermud** [comment]
I checked merge with reference implantation. Fix seems fine.
