### ISSUE TITLE
wmsops-getfeatureinfo-params-query_layers-3 and wmsops-getfeatureinfo-params-query_layers-4 wrong content-type

### ISSUE THREAD

**Issue by segoerke** [opengeospatial/ets-wms11#23]
Both test cases do not allow to include a charset in the content-type definition:

[FAIL] Expected Content-Type 'text/xml', 
	  but received 'text/xml; charset=utf-8'

This should be fixed.

**Comment by dbretschneider** [comment]
I have added a XPath Contains expression to check, if the `Content-Type` of the response contains the expected ```Content-Type```.

See Pull request: https://github.com/opengeospatial/ets-wms11/pull/26

**Comment by segoerke** [comment]
https://github.com/opengeospatial/ets-wms11/pull/26
