### ISSUE TITLE
GFI tests executed without choosing GFI for testing

### ISSUE THREAD

**Issue by segoerke** [opengeospatial/ets-wms11#24]
GFI tests are executed even though GFI was not chosen for testing.

**Comment by dbretschneider** [comment]
I have executed the actual ```ets-wms11``` branch ```master``` with following configuration:
 * ```UpdateSequence Values``` » ```Automatic```
 * ```Certification Profile``` » ```BASIC```

The test session results contains ```GetFeatureInfo``` tests. So I can reproduce the issue, But I cannot find any references between the basic and queryable profile.

In my opinion the selection of one profile has no impact which profile will be executed.

**Comment by dbretschneider** [comment]
My opinion was wrong. The test suite contains a wrong if condition. I have updated the tests and executed against RI. Issue is fixed now.

Pull request: https://github.com/opengeospatial/ets-wms11/pull/27

**Comment by segoerke** [comment]
https://github.com/opengeospatial/ets-wms11/pull/27
