### ISSUE TITLE
wms:wmsops-getmap-each-style

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms11#32]
While executing this services
http://ogc.intergraph.com/WMS2015-CITE/service.svc/get?request=GetCapabilities&service=WMS&VERSION=1.1.1

An error is detected:

1.  Test wms:wmsops-getmap-each-style 
2.  Assertion: For each of the Styles in the capabilities document, when a GetMap request is made with the STYLES parameter set to the element of the style, then the response is valid.
3.  A sequence of more than one item is not allowed as the first argument of string() (<Name/>, <Name/>, ...) 
Result: Failed

it might be a bug:
 Assertion indicates failure while there is no request sent to the WMS (no information in the wms log). 

What is going wrong?

**Comment by rjmartell** [comment]
The "sequence of more than one item is not allowed..." message indicates that only one value was expected in some context but more than one was found. Either the instance is invalid or the assertion check doesn't allow for multiple occurrences even in valid instances (which is a bug in the script). I'll take a look.

**Comment by rjmartell** [comment]
In the `wmsops-getmap-each-style` test, the string function is used to identify the preferred name of the layer having the specified style name ('Default' in this case):

```xml
<ctl:with-param name="preferred-name" select="string($capabilities/Capability//Layer[Name and Style/Name = $style]/Name)"/>
```

There are 12 layer names in the capabilities document that match, but only one is expected. Hence the error.

**Comment by rjmartell** [comment]
Well, the WMS 1.1.1 spec (OGC 01-068r3, dated 2002-01-16 and deprecated years ago) does prohibit the reuse of style names in _descendant_ layers, but not _sibling_ layers (7.1.4.5.4).

**Comment by rjmartell** [comment]
The workaround is to ensure that layer-specific styles have unique names.

**Comment by segoerke** [comment]
I think the workarround does not work arround anything important here. The problem is, that 
```
<ctl:with-param name="preferred-name" select="string($capabilities/Capability//Layer[Name and Style/Name = $style]/Name)"/> 
```
simply matches more than one item, but only one element was expected.
The most important thing is, that it is compliant behaviour that the style names are used more than one time.

**Comment by rjmartell** [comment]
The "workaround" I suggested was intended as a short-term solution for running the current suite. If the test suite were amended to allow sibling layers having the same style name, then it becomes moot.

**Comment by segoerke** [comment]
This issue is related to https://github.com/opengeospatial/ets-wms11/issues/3
