### ISSUE TITLE
Error in call to extension function

### ISSUE THREAD

**Issue by drnextgis** [opengeospatial/ets-wms11#34]
Trying to test our WMS server [here](http://cite.opengeospatial.org/teamengine) and get the following result:

```
Test wms:basic_elements-param_rules-order_and_case-3 type Mandatory default result Passed (s0002/d1e771_1)

Assertion: When a GetCapabilities request contains a parameter which is not defined by the spec, the result is valid.

Request d1e2170_1:
   Method: get
   URL: SeRvIcE=WMS&BoGuS=ignored&ReQuEsT=GetCapabilities&VeRsIoN=1.1.1
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.MalformedURLException: no protocol: ?SeRvIcE=WMS&BoGuS=ignored&ReQuEsT=GetCapabilities&VeRsIoN=1.1.1
Result: Failed
```

Problems with WMS server or issue of test suite?

**Comment by segoerke** [comment]
Cannot be reproduced without any more hint about the software under test. Please try again and additionally on the beta testsuite: http://cite.opengeospatial.org/te2

**Comment by drnextgis** [comment]
Also get Java error:

```
Log for test s0001

Test wms:wms_main type Mandatory default result Passed (s0001)

Assertion: This WMS is valid

Request d1e378_1:
   Method: get
   URL: demo.nextgis.ru/ngw/api/resource/12/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.MalformedURLException: no protocol: demo.nextgis.ru/ngw/api/resource/12/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1
Result: Failed
```

**Comment by bermud** [comment]
@drnextgis  Try to do http://demo ...
@segoerke, Here are the logs, so you can investigate further the issue
http://cite.opengeospatial.org/pub/cite/files/logs/wms111-issue34.zip

**Comment by dstenger** [comment]
Second error: MalformedURLException: no protocol: demo.nextgis.ru/ngw/api/resource/12/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1

Answer: The "http://" was missing when entering the URL.

First error: MalformedURLException: no protocol: ?SeRvIcE=WMS&BoGuS=ignored&ReQuEsT=GetCapabilities&VeRsIoN=1.1.1

Answer: The WMS [1] does not return a valid capabilities response as the document is not bound to any namespace. Thus, the test suite cannot parse the DCP URLs.

[1] ​http://demo.nextgis.ru/ngw/api/resource/12/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1

**Comment by sprd16** [comment]
Trying to test our WFS server here and get the following result:

URL: http://192.168.100.165:9090/geoserver/test/wfsversion=1.1.0#request=GetCapabilities,service=WFS
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException
Result: Failed

**Comment by lgoltz** [comment]
@sprd16 I've created a new ticket from your comment (https://github.com/opengeospatial/ets-wfs11/issues/78) as you describe a WFS issue which is not related to the problem described here. Please take a look in the new issue and try to answer the questions there.
