### ISSUE TITLE
Documentation problems for WMS 1.1.1

### ISSUE THREAD

**Issue by simgislab** [opengeospatial/ets-wms11#35]
There are few problems with docs when I visit http://cite.opengeospatial.org/teamengine/about/wms/1.1.1/site/

1. Description about the test data is [here.]
But here is not the hyperlink

2. Download the test data here.
Here link leads to 404

**Comment by segoerke** [comment]
This seems to be related to the deployment on the servers.

**Comment by bermud** [comment]
@dstenger. Please revise the site information and links

**Comment by dstenger** [comment]
A pull request was created to fix the erroneous links.

The pull request will be merged, when a new release is prepared.

**Comment by dstenger** [comment]
This fix will be part of the next release.
