### ISSUE TITLE
VendorSpecificCapabilities must be declared

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms11#36]
This file (end point):
http://www3.demis.nl/wms/wms.ashx?&ReQuEsT=GetCapabilities&SeRvIcE=WMS&VeRsIoN=1.1.1
fails when testing with WMS 1.1.1 r1.9

```
Getcapabilities response 2
Test wms:wmsops-getcapabilities-response-2 type Mandatory default result Passed (s0003/d1e1036_1)

Validation error at line 80, column 32:
Element type "VendorSpecificCapabilities" must be declared.
```
But if validating with Oxygen against this DTD it passes, why?
http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd

**Comment by segoerke** [comment]
My first question is, why is it important to advertise an empty element in a SUT which anyhow is optional.
It could be the case, that the TEAM Engine XMLValidatingParser expects occuring elements to be non-empty.
We are going on with investigation.

**Comment by segoerke** [comment]
As VendorSpecificCapabilities is not defined as an empty element within the OGC schema, the validation expects contents here, but there are no contents within it in the SUT.
The parsers are not considering the definition within the SUT capabilities document in that case here.

**Comment by pgrashoff** [comment]
We tested again without the optional (but empty) node. The same error message occurred. It may not be a problem with the vendor specific node, as the error message refers to a line still in the error block. Hope this helps. Kind regards, Poul

**Comment by segoerke** [comment]
After your change on the SUT side, we cannot reproduce the issue anymore.

**Comment by bermud** [comment]
@segoerke, I checked with version WMS version 1.10. The implementation is still failing. Using an XML DTD validator  (Oxygen) the GetCapabilities is Valid. Can you please investigate further?

**Comment by segoerke** [comment]
It was working after modification on the software side (see discussion above). As a quick win, I'd like to suggest to do the same thing again.

**Comment by pgrashoff** [comment]
Dear Sebastian, do you mean we should just leave out the empty node (which is supposed to be optional anyway)? We tried that before and it didn't make a difference to the error message. If you want we can try this again. Just let me know.

**Comment by segoerke** [comment]
From what I remember, changing the capabilities output lead into a successful test run for that test case.

**Comment by pgrashoff** [comment]
OK, we will do a test tomorrow. In that test we will remove the superfluous vendorspecific node. After that I will report back.

**Comment by bermud** [comment]
The DTD declares the following:
```
<!ELEMENT Capability 
          (Request, Exception, VendorSpecificCapabilities?,
	   UserDefinedSymbolization?, Layer?) >
```

`VendorSpecificCapabilities` is optional. Removing should not cause any problem. @segoerke ,we still need to check, why the test is failing.

**Comment by segoerke** [comment]
I am not sure if we really have to do anything. The reference implementation (cite.deegree.org/deegree-webservices-3.3.14/services/wms?service=WMS&request=GetCapabilities) is passing and as you are saying, it is an optional element and the test suite tests the mandatory behaviour. Sure, it would be good to make the test suite more robust. But for the moment I don't see this as a blocking issue here.

**Comment by pgrashoff** [comment]
Well, after all since this is our last "issue" remaining I guess the certification of the Demis WMS 4.4 should perhaps not be waiting for this?

**Comment by bermud** [comment]
@segoerke, 
I know we have a work around, but we should solve the problem if there is one.
Can you please explain why you have the following declared: ``` [<!ELEMENT VendorSpecificCapabilities EMPTY>]> ```, and why it fails it the element is present?

**Comment by pgrashoff** [comment]
Dear Sebastian and Luis, today we removed the vendorspecific node from the response and then it does pass. In other words the test in the team engine on an empty vendorspecificcapabilities node may need to be improved. 

For us, it is fine now. I have submitted Demis WMS 4.5 for certification. Thanks for your help!

**Comment by segoerke** [comment]
Okay, so we will enhance the test case for the future.

**Comment by pgrashoff** [comment]
Good plan, the devil is in the details
Thanks for your help :)

**Comment by dstenger** [comment]
We analyzed this problem more in detail.

This problem can be located in the TEAM Engine itself (not the test suite). The XMLValidatingParser [1] uses (in method #validateAgainstDTDList(), line 418ff) the schema referenced in the document for validation if a schema location is missing. Unfortunately, this mechanism does not consider internal sub types leading to the described error.

[1] https://github.com/opengeospatial/teamengine/blob/master/teamengine-core/src/main/java/com/occamlab/te/parsers/XMLValidatingParser.java

**Comment by bermud** [comment]
@dstenger, thank you for the investigation. I will move this to enhancement.

**Comment by dstenger** [comment]
@bermud, are further actions required? The problem of @pgrashoff is solved and a fix in TEAM Engine is not that simple.

**Comment by bermud** [comment]
@rjmartell, can you please advice. This seems to be related to the TE XMLValidatingParser. Thank you.

**Comment by rjmartell** [comment]
The current capabilities document does not include the (optional) `VendorSpecificCapabilities` element (for which there is no type declaration in the [normative DTD](http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd)). It's unclear from the discussion if it ever contained any content. If not, then trying to modify the validator to recognize an internal DTD subset doesn't seem necessary.

**Comment by rjmartell** [comment]
Note that the missing element declaration is not considered to be an error according to the [XML 1.0 spec](http://www.w3.org/TR/xml/#elemdecls):

> At user option, an XML processor MAY issue a warning when a declaration mentions an element type for which no declaration is provided, but this is not an error.

Presumably this allows the type declaration to appear in an internal subset (which takes priority).

**Comment by rjmartell** [comment]
Once [teamengine-135](/opengeospatial/teamengine/issues/135) is resolved, the included DTD subset should be used to validate the vendor-specific extensions.
