### ISSUE TITLE
Teamengine Beta WMS 1.1.1 tests seem to be broken

### ISSUE THREAD

**Issue by segoerke** [opengeospatial/ets-wms11#38]
On BETA, it seems that die installation of TEAM Engine for WMS 1.1.1 is broken.

Testing ends up after a few seconds with messages like:
* Error: Unable to bind function functions:append-kvp
Result: Failed
* java.lang.ClassNotFoundException: com.occamlab.ctlfns.JaxenFunction
Result: Failed

Which message is shown belongs to the SUT

**Comment by bermud** [comment]
What end point are you testing? I just restarted the server. Can you please check again.

**Comment by segoerke** [comment]
It is working correctly now.
