### ISSUE TITLE
wmsops-getmap-each-srs does not handle AUTO correctly

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ets-wms11#39]
wmsops-getmap-each-srs just substitutes each SRS entry that the server provides. 

That doesn't work for the AUTO cases (see WMS 1.1.1 section 6.5.5.2: http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#basic_elements.params.srs), which need to be completed. 

For example, if the capabilities statement says: <SRS>AUTO:42003</SRS> then it is not correct to just use:

    ...BbOx=0,0,1,1&SrS=AUTO%3A42003&WiDtH=100&FoRmAt=image%2Fpng&HeIgHt=100&VeRsIoN=1.1.1&StYlEs=&ReQuEsT=GetMap

but rather:

    ...BbOx=0,0,1,1&SrS=AUTO%3A42003,9001,-100,45&WiDtH=100&FoRmAt=image%2Fpng&HeIgHt=100&VeRsIoN=1.1.1&StYlEs=&ReQuEsT=GetMap

Suggest either handling AUTO properly, or filtering those out of the wmsops-getmap-each-srs test.

**Comment by segoerke** [comment]
The Testsuite and -data is not created for support of the AUTO namespace.

**Comment by bradh** [comment]
@segoerke : I don't understand your comment. This is not data specific - the test currently checks whatever the server returns as a supported SRS, and it is valid for the server to return SRS in the AUTO namespace. If it isn't supported, then it should be filtered out in the ETS.

**Comment by segoerke** [comment]
Please see: http://cite.opengeospatial.org/teamengine/about/wms/1.1.1/site/Web_Map_Server.html
We can discuss, if it is the better way to filter the AUTO CRS things out but from my point of view it is very clear from the requirements, that the server has only to support the mandatory CRS and EPSG:4326

**Comment by bradh** [comment]
I'm not arguing that AUTO should be required. I'm arguing that the test shouldn't fail if the server chooses to support it. Right now, that fails on GeoServer.

**Comment by bradh** [comment]
PR at https://github.com/opengeospatial/ets-wms11/pull/41

**Comment by dstenger** [comment]
Thank you for your PR. We will review and merge it to the master.

**Comment by dstenger** [comment]
Pull request was merged to master branch. This fix will be part of the next release.
