### ISSUE TITLE
wms:wmsops-getmap-params-exceptions-6 fails for gif images with indexed tranparency

### ISSUE THREAD

**Issue by matsoo** [opengeospatial/ets-wms11#40]
Our server returns an blank image exception gif with a single color with is indexed as transparent, but the test still fails with the error message: Neither alpha channel exists nor tRNS chunk exists.

Here is the exact URL used in the test:
http://192.71.92.21/MapService/wms.axd/WmsTestData?&VeRsIoN=1.1.1&BbOx=-1,-1,1,1&TrAnSpArEnT=TRUE&LaYeRs=NonExistant&FoRmAt=image/gif&StYlEs=&ExCePtIoNs=application/vnd.ogc.se_blank&SrS=EPSG:4326&ReQuEsT=GetMap&WiDtH=100&HeIgHt=100

**Comment by dstenger** [comment]
Issue was fixed in pull request #45 and will be part of the next release.

**Comment by dstenger** [comment]
Pull request was merged into master branch. Fix will now be included in the next release.
