### ISSUE TITLE
DTD - wmsops-getcapabilities-response-2

### ISSUE THREAD

**Issue by emoiroux** [opengeospatial/ets-wms11#44]
Hi, 

The following test "wms:wmsops-getcapabilities-response-2" fails. 
It's look like i'm using the wrong DTD.
I'm currently using http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd

Here is my configuration :
Service : http://my_wms_server/wms1_1_1/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities
Platform : http://cite.opengeospatial.org/te2
Service : WMS 1.1.1 rev.1.10

Similar issue : https://github.com/opengeospatial/ets-wms11/issues/2

Thanks, 
Etienne

**Comment by emoiroux** [comment]
Test failed with http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd or 
http://schemas.opengis.net/wms/1.1.1/WMS_MS_Capabilities.dtd

**Comment by bermud** [comment]
@emoiroux, thank you for reporting we will investigate

**Comment by dstenger** [comment]
Response given by R. Martell in the forum:

> 1. wmsops-getcapabilities-response-2

> There are several validation errors: “The content of element type "Layer" must match "(Name?,Title,Abstract?,…”
> Note that Title must follow Name.

**Comment by dstenger** [comment]
For further investigation I need more information why the test fails (e.g. log).
The test server you provided is not accessible anymore.

**Comment by emoiroux** [comment]
It's fine for me now. You can close the issue. the file "http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd" is fine too.
