### ISSUE TITLE
"application/vnd.ogc.gml" not a mandatory GetFeatureInfo format

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wms11#48]
The CITE WMS 1.1.1 test suite tests for "application/vnd.ogc.gml" as a mandatory GetFeatureInfo format.  However, the specification doesn't dictate it as a required format.  It's mentioned only as an example.

**Comment by bermud** [comment]
@pomakis. we will back to you very soon. Thank you for reporting.

**Comment by dstenger** [comment]
Hello,
thank you for reporting.
Which test are you referring to? "wms:wmsops-getfeatureinfo-params-info_format-2"?
This test is just enabled if you select "GML FeatureInfo" on the start page of the ETS. These are optional tests and "The remaining tests are not required for certification, but may prove informative or be useful as a debugging aid.".
All other tests do not require "application/vnd.ogc.gml" as a mandatory GetFeatureInfo format.

**Comment by pomakis** [comment]
Yes, you're right.  I neglected to notice that the "GML FeatureInfo" test was optional and explicitly states that it tests with the application/vnd.ogc.gml GetFeatureInfo format.  I withdraw this issue.
