### ISSUE TITLE
LayerNotDefined - Assertion

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms11#5]
This tests fail:  

**Test wms:wmsops-getmap-params-layers-5**:  
Assertion: When the layer in a GetMap request is invalid, then the response is
an exception (code=&quot;LayerNotDefined&quot;).  

**Test wms:wmsops-getmap-params-layers-6**:  
Assertion: When a GetMap request contains two layers where the first is valid
and the second is invalid, then the response is an exception
(code=&quot;LayerNotDefined&quot;).  

but the SUT answers in both cases (imho correctly):  

```
<?xml version="1.0" encoding="utf-8" standalone="no" ?>  
<!DOCTYPE ServiceExceptionReport SYSTEM  
"http://services.interactive-
instruments.de/cite2013wfs/cite/schema/ogc/wms/1.1.1/exception_1_1_1.dtd">  
<ServiceExceptionReport version="1.1.1">  
    <ServiceException code="LayerNotDefined"> Request rejected due to errors. InternalExceptionCode:  
        iiLayerNotDefined. Reason: <![CDATA[  
The requested layer "NonExistant" is not supported.  
]]>  
    </ServiceException>  
</ServiceExceptionReport>  
```

The test  
**wmsops-getmap-params-layers-7** _**passes**_ (the SUT answers the same as above) and the assertion in the sources is the same for all three tests:   

<xsl:variable name="expression">not(boolean(/ServiceExceptionReport/ServiceExc
eption[@code='LayerNotDefined']))/xsl:variable  

Not sure what is going on here.

[Originally reported in the OGC CITE issue tracker: issue #952](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=952)  

_Opened: 2014-07-07 07:26:55 Last Updated: 2014-07-07 09:39:02_

**Comment by dineshahuja** [comment]
For our test cases for WMS 1.1.1 we are having the same problem as stated above.
Test wms:wmsops-getmap-params-layers-5
Test wms:wmsops-getmap-params-layers-6 are failing on r7 where as 

Test wms:wmsops-getmap-params-layers-7 is passing.

Returned exception code is same in all above cases code="LayerNotDefined".

Please suggest
