### ISSUE TITLE
missing urlencoding

### ISSUE THREAD

**Issue by swen100** [opengeospatial/ets-wms11#50]
Hello,
 
some of the WMS 1.1/1.3 tests fail because the request-url does not follow the standard in encoding reserved characters.

For example in the “wms:wmsops-getmap-params-exceptions-2”-test there is a parameter “FoRmAt” with a missing encoding of the whitespace-character in the value:
“...&FoRmAt=image/png; mode=24bit&...”

It should be: “...&FoRmAt=image/png;**%20**mode=24bit&...“

see https://en.wikipedia.org/wiki/Percent-encoding

Spaces must be encoded for servers to accept them as normal characters in values, otherwise they identify the term after the whitespace as request-method (normally “HTTP/1.1”). So the interpretion of the parameters end at this point and all other subsequent parameters will not be parsed, which leads to false-errors.

**Comment by dstenger** [comment]
Thank you for reporting this issue. We will do further investigation.

**Comment by dstenger** [comment]
You are right. The format value is not encoded by the test suite.

Can you provide a service we can use to test a fix?

**Comment by swen100** [comment]
sure, u can use this one (only available for requests from http://cite.opengeospatial.org):
https://wms.onmaps.de?key=3b8a499f437e2b6c2c164df4f036537d&service=wms

**Comment by dstenger** [comment]
We are currently working on a fix.

**Comment by dstenger** [comment]
A fix was created and is provided via pull request #51.
The pull request will be merged right before the next release is built.

**Comment by dstenger** [comment]
The fix was successfully tested and merged into master branch.
It will be part of the upcoming release.
