### ISSUE TITLE
No Rest API

### ISSUE THREAD

**Issue by pblottiere** [opengeospatial/ets-wms11#52]
Hi,

I would like to run ets-wms11 tests thanks to the Rest API as I'm doing it with ets-wms13, ets-gml32 or ets-wfs20 but it does not seem to be available on the page http://localhost:8080/teamengine/rest/suites/.

I have installed/unarchived the next packages after the compilation step:
- ets-wms11-1.15-deps.zip in $(TE_BASE)/resources/lib
- ets-wms11-1.15-site.jar in $(TE_BASE)/resources/lib
- ets-wms11-1.15-ctl.zip in $(TE_BASE)/scripts

Versions currently used:
- teamengine: 4.10
- ets-wms11: 1.15
- Ubuntu 16.04.1 LTS

Am I missing something?

Thank you for your work!

**Comment by dstenger** [comment]
We created a pull request to enable REST API: #56.

This is an example request how to run tests with the REST interface: http://host/teamengine/rest/suites/wms/1.16-SNAPSHOT/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms111?service=WMS%26request=GetCapabilities

To enable EARL reporting following fix has to be included in TEAM Engine installation: https://github.com/opengeospatial/teamengine/issues/219

EARL report is limited until following issue is solved: #53

**Comment by pblottiere** [comment]
Nice! Thank you @dstenger for taking care of it!
