### ISSUE TITLE
Update CTL with better information about conformance classes 

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wms11#53]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
I think we can decide between the following conformance classes (as in WMS 1.3): 
 * basic
 * queryable

Furthermore there are some additional conformance classes:
 * Recommendation Support
 * GML FeatureInfo
 * Fees and Access Constraints
 * BoundingBox Constraints

CC `basic` should be configured as basic (required for certification).

**Comment by lgoltz** [comment]
Test was restructured to be grouped by profiles as described in https://github.com/opengeospatial/ets-wms11/issues/53#issuecomment-378240534

'no' and 'basic' was configured as basic: https://github.com/opengeospatial/ets-wms11/pull/57/commits/b8c7db6c7c249358498d2703eb01876f816393ac

Currently the organisation of the tests is confusing. On the main page of the WebGUI one of the three  profiles can be select:
  * NONE - Do not certify that the server meets requirements for any test profile
  * BASIC - Certify that the server meets all requirements for the BASIC profile
  * QUERYABLE - Certify that the server meets all requirements for the QUERYABLE profile

The executed tests differs depending on the selected profile: 
 * NONE: only tests assigned to NONE are executed
 * BASIC: tests assigned to NONE and BASIC are executed
 * QUERYABLE: tests assigned to NONE and QUERYABLE are executed

If QUERYABLE is selected the BASIC tests are not executed (and in the new HTML report only NONE is marked as basic conformance class). 

The problem will be discussed in a new ticket.  

See also Ia in https://opengeospatial.github.io/ets-wms11/Web_Map_Server.html
