### ISSUE TITLE
Improve organisation of tests

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms11#58]
As described in https://github.com/opengeospatial/ets-wms11/issues/53#issuecomment-378842640 the organisation of the tests is confusing. On the main page of the WebGUI one of the three  profiles can be select:
  * NONE - Do not certify that the server meets requirements for any test profile
  * BASIC - Certify that the server meets all requirements for the BASIC profile
  * QUERYABLE - Certify that the server meets all requirements for the QUERYABLE profile

The executed tests differs depending on the selected profile: 
 * NONE: only tests assigned to NONE are executed
 * BASIC: tests assigned to NONE and BASIC are executed
 * QUERYABLE: tests assigned to NONE and QUERYABLE are executed

If QUERYABLE is selected the BASIC tests are not executed (and in the new HTML report only NONE is marked as basic conformance class).

This must be discussedin the context of the new HTML report.

**Comment by ghobona** [comment]
The standard says:

_2.1 Conformance classes and requirements_

This International Standard defines **two conformance classes, one for a basic WMS, and the other for a queryable WMS**. Each has two subclasses, one for clients and the other for servers.

_2.2 Basic WMS_

A basic WMS shall support the basic service elements (see Clause 6), the GetCapabilities operation (see 7.2), and the GetMap operation (see 7.3). To conform to this International Standard, a basic WMS shall satisfy the requirements of A.1 of the Abstract Test Suite in Annex A.

_2.3 Queryable WMS_

**A queryable WMS shall satisfy all the requirements for a basic WMS**, and shall also support the GetFeatureInfo operation (see 7.4). To conform to this International Standard, a queryable WMS shall satisfy all requirements of the Abstract Test Suite in Annex A.

**Comment by keshav-nangare** [comment]
As per discussion, I have updated the test behaviour as per user inputs and removed the NONE profile from UI.
The following behaviour is updated:
1. BASIC: Only Basic profiles test will be executed.
2. QUERYABLE: Basic + Queryable profiles will be executed.

Please find the changes in the #77 PR.

**Comment by dstenger** [comment]
Currently, the integration-tests are failing when running the build with `mvn clean install site docker:run -Pintegration-tests,docker`.
It looks like that the start of `wms:wms-no-profile` was removed in the pull request. However, the tests shall still be executed when selecting BASIC or QUERYABLE. Just the option to execute NONE only shall be removed.

**Comment by keshav-nangare** [comment]
@dstenger 

I have updated condition that will execute NONE profile tests and also updated integration tests pass count, iut. Please find the changes in the same PR.
