### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms11#59]
It is required to improve the documentation of the ETS:
 * Section Reference Implementations on https://opengeospatial.github.io/ets-wms11/ 
  * links are outdated (could be replaced by a link to the wiki page
 * WebGUI entry page: Link in section 'Certification Profile' is outdated

**Comment by dstenger** [comment]
Please replace links to single services (RIs) by https://github.com/opengeospatial/cite/wiki/Reference-Implementations.

**Comment by dstenger** [comment]
@bermud Link to http://cite.opengeospatial.org/tsOGC/ViewTestSpec?SPEC=Web_Map_Server.html&TYPE=AVAILABLE&sesstype=OGC#A.-Certification%20Requirements is dead. Do you know where I find a reachable version of this document?

**Comment by bermud2** [comment]
Web_Map_Server.html
<https://github.com/opengeospatial/ets-wms11/blob/master/src/site/resources/Web_Map_Server.html>
is
here:
https://github.com/opengeospatial/ets-wms11/tree/master/src/site/resources

Best Regards,

Luis

----

Luis E. Bermudez, Ph.D.
Executive Director Innovation Program
Open Geospatial Consortium (OGC)

https://www.linkedin.com/in/bermudez
Skype: bermudez_luis Twitter: @berdez
Tel: +1 301 760 7323
lbermudez@ogc.org

**Comment by dstenger** [comment]
Please use following URL: https://opengeospatial.github.io/ets-wms11/Web_Map_Server.html

**Comment by keshav-nangare** [comment]
Update documentation with new URL's
