### ISSUE TITLE
Test wms:wmsops-getcapabilities-params-request-1 uses wrong request parameter value

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wms11#60]
The source code uses "capabilities" for request parameter. Instead, "GetCapabilities" should be used.

That may be for WMS 1.0.0 backward compatibility but is not normative for WMS 1.1.1.

**Comment by keshav-nangare** [comment]
Updated the request parameter. Commit: 3f23cd016171228d02a7a0073d5b585b8ced776f
