### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wms11#62]
See opengeospatial/ets-wms13#56 for instructions.

Please use following service implementation: http://cite.deegree.org/deegree-webservices-3.4.0/services/wms111?service=WMS&request=GetCapabilities

**Comment by dstenger** [comment]
@keshav-nangare 
Thank you for your work.
However, https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI was updated and extended by integration tests.
Can you please update this pull request considering current extended documentation?

**Comment by dstenger** [comment]
Also, Docker configuration must be updated as described in https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites.

**Comment by keshav-nangare** [comment]
@dstenger 

I have updated the SoapUI script, docker maven configuration and jenkinsfiles according to the latest document.
