### ISSUE TITLE
Test wms:wmsops-getmap-each-style fails if layer with the same name occurs multiple times

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms11#65]
Tested locally with the current master (1.18-SNAPSHOT) and TEAM Engine 5.3 (docker environment).

Following error is logged in the tomcat:

```
Fatal Error: Cannot convert string "0 0 0 0 0 0 0 0 0 0 0" to a double; SystemID: file:/root/te_base/work/_root_te_base_scripts_wms_1.1.1_ctl_main.xml/functions$boolean-as-integer.fn; Line#: 55; Column#: -1
Fatal Error: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function java.lang.RuntimeException: net.sf.saxon.s9api.SaxonApiException: Cannot convert string "0 0 0 0 0 0 0 0 0 0 0" to a double; SystemID: file:/root/te_base/work/_root_te_base_scripts_wms_1.1.1_ctl_main.xml/wms$wmsops-getmap-each-style.test; Line#: 101; Column#: -1
```

Creating the layer info (calling functions:layer-info) calls function:bbox and the xpath `$root-layer/descendant-or-self::Layer[Name = $layer-name]/@noSubsets` selects all Layers/@noSubsets (in the example above 11 layers with the same name are described in the capabilities).

**Comment by keshav-nangare** [comment]
@lgoltz 

Can please provide the test service?

Not able to reproduce with following RI:

[1] http://cite.deegree.org/deegree-webservices-3.4.0/services/wms111?service=WMS&request=GetCapabilities

[2] https://services.interactive-instruments.de/ogc-reference/cite/wms?request=getcapabilities&service=wms&version=1.1.1

**Comment by lgoltz** [comment]
The service is not available any longer. I close this issue.
