### ISSUE TITLE
REST API: URI of test suite is equal to WMS 1.3 test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wms11#72]
Currently, REST URI of test suite is `[TEAM_ENGINE]/rest/suites/wms/` which is equal to WMS 1.3 test suite.

Example: See Beta environment: http://cite.opengeospatial.org/te2/rest/suites/wms/

REST URI of test suite shall contain major and minor version of specification: `[TEAM_ENGINE]/rest/suites/wms11/`

**Comment by dstenger** [comment]
Please also adjust the SoapUI project for integration tests.
Following build must be successful: `mvn clean install site -Pintegration-tests`

**Comment by keshav-nangare** [comment]
Fixed with this PR: #74

**Comment by dstenger** [comment]
Local functional test of fix was successful.
- http://localhost:8081/teamengine/rest/suites/wms11/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4.5/services/wms111?service=WMS%26request=GetCapabilities
