### ISSUE TITLE
Unknown error when attempting to test WMS OGC compliance

### ISSUE THREAD

**Issue by Samgrocock** [opengeospatial/ets-wms11#75]
I am running into issues using the compliance checker to check my Geoserver implementation. After spending some time figuring out how to load the test dataset into my Geoserver in order to run WMS 1.1.1 tests, I am getting the following error on the very first test (server URL replaced with XXX):
 
Test wms:wms_main type Mandatory default result Passed (s0034)
 
Assertion: This WMS is valid
 
Request d1e11344_1:
   Method: get
   URL: XXX
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: java.io.FileNotFoundException: XXX/schemas/wms/1.1.1/WMS_MS_Capabilities.dtd
Result: Failed
 
It seems like the get capabilities document can’t be found but the link I am giving for the test does return a valid getcapabilities xml doc as far as I can tell (I can send a copy over if it would help), and previous to this the tests were at least getting past this first stage, albeit with different errors later on in the process. Do you know what might be causing the above issue?

**Comment by dstenger** [comment]
@keshav-nangare Can you please analyse this issue?

**Comment by dstenger** [comment]
@Samgrocock Can you provide a test service to reproduce the behaviour?

**Comment by Samgrocock** [comment]
@dstenger test URL is http://test.earthsense.co.uk/api/wmsfeed?

**Comment by keshav-nangare** [comment]
@dstenger 

I have investigated the issue and found the problem. @Samgrocock  I agree, the GetCapabilities document is fine but you can see there is an element with DOCTYPE which points to the external DTD in capability document and which is not available i.e. the reason of the failure.
The teamengine is trying to parse the response but parser also trying to fetch that external DTD which returns 404 for that DTD URL which turns into immediate test failure.

**Comment by dstenger** [comment]
@Samgrocock Can you please fix the DTD URL and check if you can execute the test suite then?

**Comment by Samgrocock** [comment]
@keshav-nangare @dstenger 

Hi both, have fixed the links in the get capabilities response and all is well now. Thanks for your help and sorry about the fuss.
